version: "3.9"
services:
  db:
    container_name: postgres
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 4444:5432
  api:
    container_name: swapify
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
