import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { DarkModeProvider } from "../_components/DarkModeContext";
import { UserProvider } from "../_lib/_context/UserContext";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
  admin,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
  admin: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <DarkModeProvider>
            {admin}
            {auth}
            {children}
          </DarkModeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
